version: '3.2'

services:
  ipfs:
    container_name: {ipfs_container_name}
    image: ipfs/kubo:{ipfs_version}
    ports:
      - {ipfs_rpc_port}:5001
      - {ipfs_webui_port}:8080
      - {ipfs_node_port}:4001
      - {ipfs_node_port}:4001/udp
    volumes:
      - type: volume
        source: {ipfs_container_name}-export-volume
        target: /export
      - type: volume
        source: {ipfs_container_name}-data-volume
        target: /data/ipfs
    environment:
      IPFS_PROFILE: server
  api:
    container_name: api
    build:
      context: moonstorage-web-api
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./moonstorage-web-api
        target: /app/
  nginx:
    container_name: nginx
    build:
      context: moonstorage-web-api
      dockerfile: ./Dockerfile-nginx
    ports:
      - 5000:5000
    links:
      - api
    volumes:
      - type: bind
        source: ./moonstorage-web-api/nginx.conf
        target: /etc/nginx/conf.d/default.conf

volumes:
  {ipfs_container_name}-export-volume:
  {ipfs_container_name}-data-volume: